spring:
    http:
      encoding:
        charset: UTF-8
        encoding: true
        force: true
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://localhost:3306/balerocms_enterprise?useUnicode=yes&characterEncoding=UTF-8
        databaseName:
        serverName:
        username: root
        password:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    jpa:
      show_sql: false
      hibernate:
        ddl-auto: update
    thymeleaf:
      cache: false
      encoding: UTF-8
      content-type: text/html
    logging:
      level:
          org:
            springframework:
              web: DEBUG
          hibernate: OFF
flyway:
  validateOnMigrate: false
  locations: classpath:db/migration