spring:
    http:
    encoding:
      charset: UTF-8 # the encoding of HTTP requests/responses
      enabled: true # enable http encoding support
      force: true # force the configured encoding
    datasource:
        dataSourceClassName: org.h2.jdbcx.JdbcDataSource
        url: jdbc:h2:mem:balerocms_enterprise;DB_CLOSE_DELAY=-1
        databaseName:
        serverName:
        username:
        password:
    jpa:
      show_sql: true
      hibernate:
        ddl-auto: validate
    thymeleaf:
      cache: false
      encoding: UTF-8
      content-type: text/html
    logging:
      level:
          org:
            springframework:
              web: DEBUG
          hibernate: ERROR
flyway:
  locations: classpath:dev/db/migration